// Auto-generated. Pages are embedded as base64 below.
const DASH_HTML_B64 = "PCFkb2N0eXBlIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgo8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEiIC8+Cjx0aXRsZT5MaXZlQ2hhdCBCYWQtUmF0aW5nIE1vbml0b3I8L3RpdGxlPgo8bGluayByZWw9Imljb24iIHR5cGU9ImltYWdlL3N2Zyt4bWwiIGhyZWY9Ii9mYXZpY29uLnN2ZyIvPgo8c3R5bGU+CiAgOnJvb3R7LS1iZzojMGYxNzJhOy0tY2FyZDojMTExYzMzOy0tbGluZTojMjIzMDRkOy0tdHh0OiNlN2VlZmM7LS1tdXQ6IzhiYTBjNDstLWFjY2VudDojM2I4MmY2Oy0tcmVkOiMzYTFkMjQ7LS1yZWRiOiNmZjVkNmM7LS1ncmVlbjojMzRkMzk5fQogICp7Ym94LXNpemluZzpib3JkZXItYm94fQogIGJvZHl7bWFyZ2luOjA7Zm9udDoxNHB4LzEuNDUgc3lzdGVtLXVpLFNlZ29lIFVJLFJvYm90byxBcmlhbDtjb2xvcjp2YXIoLS10eHQpOwogICAgYmFja2dyb3VuZDpyYWRpYWwtZ3JhZGllbnQoMTIwMHB4IDYwMHB4IGF0IDE1JSAtMTAlLCMxYjJiNTIgMCUsdHJhbnNwYXJlbnQgNjAlKSwKICAgICAgICAgICAgICAgcmFkaWFsLWdyYWRpZW50KDEwMDBweCA1MDBweCBhdCAxMDAlIDAlLCMwZjJmNDUgMCUsdHJhbnNwYXJlbnQgNTUlKSwKICAgICAgICAgICAgICAgbGluZWFyLWdyYWRpZW50KDE4MGRlZywjMGIxNDI2LCMwZjE3MmEgNDAlLCMwYTExMjApfQogIGhlYWRlcntwb3NpdGlvbjpzdGlja3k7dG9wOjA7ei1pbmRleDo1O3BhZGRpbmc6MTBweCAxNnB4O2Rpc3BsYXk6ZmxleDtmbGV4LXdyYXA6d3JhcDtnYXA6OHB4O2FsaWduLWl0ZW1zOmNlbnRlcjsKICAgIGJhY2tncm91bmQ6bGluZWFyLWdyYWRpZW50KDkwZGVnLHJnYmEoNTksMTMwLDI0NiwuMTYpLHJnYmEoMTQsMTY1LDIzMywuMDgpIDQ1JSxyZ2JhKDE2LDE4NSwxMjksLjEwKSk7YmFja2Ryb3AtZmlsdGVyOmJsdXIoMTBweCk7Ym9yZGVyLWJvdHRvbToxcHggc29saWQgdmFyKC0tbGluZSl9CiAgaDF7Zm9udC1zaXplOjE1cHg7bWFyZ2luOjAgMTBweCAwIDB9CiAgaW5wdXQsc2VsZWN0e2JhY2tncm91bmQ6IzBiMTQyNjtjb2xvcjp2YXIoLS10eHQpO2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSk7Ym9yZGVyLXJhZGl1czo4cHg7cGFkZGluZzo3cHggMTBweH0KICAjc2VhcmNoe21pbi13aWR0aDoyMDBweH0KICBidXR0b257YmFja2dyb3VuZDojMWMyYzRhO2NvbG9yOnZhcigtLXR4dCk7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtib3JkZXItcmFkaXVzOjhweDtwYWRkaW5nOjdweCAxMnB4O2N1cnNvcjpwb2ludGVyfQogIGJ1dHRvbjpob3Zlcntib3JkZXItY29sb3I6dmFyKC0tYWNjZW50KX0KICBidXR0b24ucHJpbWFyeXtiYWNrZ3JvdW5kOmxpbmVhci1ncmFkaWVudCgxMzVkZWcsIzNiODJmNiwjMDZiNmQ0KTtib3JkZXItY29sb3I6IzNiODJmNjtjb2xvcjojZmZmO2ZvbnQtd2VpZ2h0OjYwMDtib3gtc2hhZG93OjAgOHB4IDIycHggLTEwcHggIzNiODJmNn0KICBidXR0b24ucHJpbWFyeTpob3ZlcntmaWx0ZXI6YnJpZ2h0bmVzcygxLjA4KX0KICAucXtwYWRkaW5nOjZweCAxMHB4O2ZvbnQtc2l6ZToxMnB4fQogICNzdGF0dXN7Y29sb3I6dmFyKC0tbXV0KTttYXJnaW4tbGVmdDphdXRvfQogIC53cmFwe3BhZGRpbmc6MTRweCAxNnB4IDYwcHh9CiAgLmNhcmRze2Rpc3BsYXk6ZmxleDtmbGV4LXdyYXA6d3JhcDtnYXA6MTBweDttYXJnaW4tYm90dG9tOjEycHh9CiAgLmNhcmR7YmFja2dyb3VuZDpsaW5lYXItZ3JhZGllbnQoMTYwZGVnLHJnYmEoNTksMTMwLDI0NiwuMTQpLHJnYmEoMTM5LDkyLDI0NiwuMDYpKSx2YXIoLS1jYXJkKTtib3JkZXI6MXB4IHNvbGlkICMyYjNmNjM7Ym9yZGVyLXJhZGl1czoxNHB4O3BhZGRpbmc6MTJweCAxNnB4O21pbi13aWR0aDoxMzBweDtib3gtc2hhZG93OjAgMTJweCAzMHB4IC0yMnB4ICMwMDB9CiAgLmNhcmQgLm57Zm9udC1zaXplOjIycHg7Zm9udC13ZWlnaHQ6ODAwO2JhY2tncm91bmQ6bGluZWFyLWdyYWRpZW50KDEzNWRlZywjOTNjNWZkLCNhN2YzZDApOy13ZWJraXQtYmFja2dyb3VuZC1jbGlwOnRleHQ7YmFja2dyb3VuZC1jbGlwOnRleHQ7Y29sb3I6dHJhbnNwYXJlbnR9CiAgLmNhcmQgLmx7Y29sb3I6dmFyKC0tbXV0KTtmb250LXNpemU6MTJweH0KICAudGFic3tkaXNwbGF5OmZsZXg7ZmxleC13cmFwOndyYXA7Z2FwOjhweDttYXJnaW46NnB4IDAgMTJweH0KICAudGFie3BhZGRpbmc6N3B4IDEycHg7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtib3JkZXItcmFkaXVzOjk5OXB4O2N1cnNvcjpwb2ludGVyO2JhY2tncm91bmQ6IzBiMTQyNn0KICAudGFiLmFjdGl2ZXtiYWNrZ3JvdW5kOmxpbmVhci1ncmFkaWVudCgxMzVkZWcsIzNiODJmNiwjOGI1Y2Y2KTtib3JkZXItY29sb3I6IzYzNjZmMTtjb2xvcjojZmZmO2ZvbnQtd2VpZ2h0OjYwMH0KICB0YWJsZXt3aWR0aDoxMDAlO2JvcmRlci1jb2xsYXBzZTpjb2xsYXBzZTtiYWNrZ3JvdW5kOnZhcigtLWNhcmQpO2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSk7Ym9yZGVyLXJhZGl1czoxMnB4O292ZXJmbG93OmhpZGRlbn0KICB0aCx0ZHtwYWRkaW5nOjdweCA5cHg7Ym9yZGVyLWJvdHRvbToxcHggc29saWQgdmFyKC0tbGluZSk7dGV4dC1hbGlnbjpsZWZ0O3ZlcnRpY2FsLWFsaWduOnRvcDtmb250LXNpemU6MTIuNXB4fQogIHRoe2JhY2tncm91bmQ6bGluZWFyLWdyYWRpZW50KDE4MGRlZywjMTIyMDNjLCMwZDE3MjkpO2NvbG9yOiNhOWJkZTB9CiAgdHIuc2hhcmVkIHRke2JhY2tncm91bmQ6dmFyKC0tcmVkKX0KICB0cjpob3ZlciB0ZHtiYWNrZ3JvdW5kOiMxNjI0NDN9CiAgLmJhZGdle2Rpc3BsYXk6aW5saW5lLWJsb2NrO3BhZGRpbmc6MnB4IDhweDtib3JkZXItcmFkaXVzOjk5OXB4O2ZvbnQtc2l6ZToxMXB4O2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSl9CiAgLmJhZGdlLmJhZHtiYWNrZ3JvdW5kOiMzYTFkMjQ7Y29sb3I6dmFyKC0tcmVkYik7Ym9yZGVyLWNvbG9yOiM1YjI2MzB9CiAgLmJhZGdlLmdvb2R7YmFja2dyb3VuZDojMTIzMDI0O2NvbG9yOnZhcigtLWdyZWVuKTtib3JkZXItY29sb3I6IzFkNGQzN30KICAuYmFkZ2UudW57YmFja2dyb3VuZDojMjQyYjNhO2NvbG9yOnZhcigtLW11dCl9CiAgYXtjb2xvcjojN2FiN2ZmO3RleHQtZGVjb3JhdGlvbjpub25lO2N1cnNvcjpwb2ludGVyfWE6aG92ZXJ7dGV4dC1kZWNvcmF0aW9uOnVuZGVybGluZX0KICBhLmV4dHtjb2xvcjojMzRkMzk5O2ZvbnQtd2VpZ2h0OjcwMDttYXJnaW4tbGVmdDo2cHh9CiAgLmVtcHR5e3BhZGRpbmc6MzBweDt0ZXh0LWFsaWduOmNlbnRlcjtjb2xvcjp2YXIoLS1tdXQpfQogIC5ub3Rle2JhY2tncm91bmQ6dmFyKC0tY2FyZCk7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtib3JkZXItcmFkaXVzOjEycHg7cGFkZGluZzoxMnB4IDE0cHg7bWFyZ2luLWJvdHRvbToxMnB4fQogIC5ub3RlIHRhYmxle3dpZHRoOmF1dG87YmFja2dyb3VuZDp0cmFuc3BhcmVudDtib3JkZXI6bm9uZX0ubm90ZSB0ZHtwYWRkaW5nOjRweCAxMnB4IDRweCAwO2JvcmRlcjpub25lfQogIC5jYWwtd3JhcHtwb3NpdGlvbjpyZWxhdGl2ZX0KICAuZGF0ZWJ0bntkaXNwbGF5OmZsZXg7YWxpZ24taXRlbXM6Y2VudGVyO2dhcDo2cHh9CiAgLmNhbHtwb3NpdGlvbjphYnNvbHV0ZTt0b3A6NDRweDtsZWZ0OjA7ei1pbmRleDozMDt3aWR0aDoyODBweDtwYWRkaW5nOjEwcHg7Ym9yZGVyLXJhZGl1czoxMnB4O2JhY2tncm91bmQ6IzBlMWEzMDtib3JkZXI6MXB4IHNvbGlkIHZhcigtLWxpbmUpO2JveC1zaGFkb3c6MCAyNHB4IDUwcHggLTI0cHggIzAwMH0KICAuY2FsLmhpZGRlbntkaXNwbGF5Om5vbmV9CiAgLmNhbC1oZHtkaXNwbGF5OmZsZXg7YWxpZ24taXRlbXM6Y2VudGVyO2p1c3RpZnktY29udGVudDpzcGFjZS1iZXR3ZWVuO21hcmdpbi1ib3R0b206OHB4fS5jYWwtaGQgYnV0dG9ue3BhZGRpbmc6MnB4IDEycHh9CiAgLmNhbC1ncmlke2Rpc3BsYXk6Z3JpZDtncmlkLXRlbXBsYXRlLWNvbHVtbnM6cmVwZWF0KDcsMWZyKTtnYXA6M3B4O3RleHQtYWxpZ246Y2VudGVyfQogIC5jYWwtZ3JpZCAuZG93e2NvbG9yOnZhcigtLW11dCk7Zm9udC1zaXplOjExcHg7cGFkZGluZzoycHggMH0KICAuY2FsLWdyaWQgLmRheXtwYWRkaW5nOjZweCAwO2JvcmRlci1yYWRpdXM6OHB4O2N1cnNvcjpwb2ludGVyfS5jYWwtZ3JpZCAuZGF5OmhvdmVye2JhY2tncm91bmQ6IzFjMmM0YX0KICAuY2FsLWdyaWQgLmRheS5zZWx7YmFja2dyb3VuZDpsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCMzYjgyZjYsIzhiNWNmNik7Y29sb3I6I2ZmZjtmb250LXdlaWdodDo3MDB9CiAgLmNhbC1ncmlkIC5kYXkudG9kYXl7Ym9yZGVyOjFweCBzb2xpZCAjMzRkMzk5fQogIC5tb2RhbHtwb3NpdGlvbjpmaXhlZDtpbnNldDowO2JhY2tncm91bmQ6cmdiYSgzLDgsMTgsLjcyKTtkaXNwbGF5Om5vbmU7YWxpZ24taXRlbXM6ZmxleC1zdGFydDtqdXN0aWZ5LWNvbnRlbnQ6Y2VudGVyO3otaW5kZXg6MjA7cGFkZGluZzoyNHB4O292ZXJmbG93OmF1dG99CiAgLm1vZGFsLm9ue2Rpc3BsYXk6ZmxleH0KICAuc2hlZXR7YmFja2dyb3VuZDp2YXIoLS1jYXJkKTtib3JkZXI6MXB4IHNvbGlkIHZhcigtLWxpbmUpO2JvcmRlci1yYWRpdXM6MTRweDt3aWR0aDptaW4oOTAwcHgsMTAwJSl9CiAgLnNoZWV0IC5oZHtwYWRkaW5nOjE0cHggMThweDtib3JkZXItYm90dG9tOjFweCBzb2xpZCB2YXIoLS1saW5lKTtkaXNwbGF5OmZsZXg7Z2FwOjEwcHg7YWxpZ24taXRlbXM6Y2VudGVyO2ZsZXgtd3JhcDp3cmFwfQogIC5zaGVldCAuYmR7cGFkZGluZzoxNnB4IDE4cHh9CiAgLnJldntiYWNrZ3JvdW5kOiMwYjE0MjY7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtib3JkZXItcmFkaXVzOjEwcHg7cGFkZGluZzoxMnB4IDE0cHg7bWFyZ2luLWJvdHRvbToxNHB4fQogIC5yZXYgLmt2e21hcmdpbjo0cHggMH0ucmV2IC5re2NvbG9yOnZhcigtLW11dCk7ZGlzcGxheTppbmxpbmUtYmxvY2s7bWluLXdpZHRoOjEyMHB4fQogIC5zZWMtaHttYXJnaW46MTJweCAwIDVweDtmb250LXdlaWdodDo3MDA7Y29sb3I6IzkzYzVmZDtib3JkZXItYm90dG9tOjFweCBzb2xpZCB2YXIoLS1saW5lKTtwYWRkaW5nLWJvdHRvbTozcHh9LnNlYy1oOmZpcnN0LWNoaWxke21hcmdpbi10b3A6MH0KICAudHJ7bWF4LWhlaWdodDo1MnZoO292ZXJmbG93OmF1dG87Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtib3JkZXItcmFkaXVzOjEwcHh9CiAgLm1zZ3twYWRkaW5nOjhweCAxMnB4O2JvcmRlci1ib3R0b206MXB4IHNvbGlkICMxYTI2M2Y7ZGlzcGxheTpmbGV4O2dhcDoxMHB4fQogIC5tc2cgLndob3ttaW4td2lkdGg6MTIwcHg7Zm9udC13ZWlnaHQ6NjAwfQogIC5tc2cuY3VzdG9tZXIgLndob3tjb2xvcjojZmNhNWE1fS5tc2cuYWdlbnQgLndob3tjb2xvcjojOTNjNWZkfS5tc2cuYm90IC53aG97Y29sb3I6I2E3ZjNkMH0KICAubXNnIC50bXtjb2xvcjp2YXIoLS1tdXQpO2ZvbnQtc2l6ZToxMXB4O21pbi13aWR0aDo2NHB4fQogIC5jbG9zZXttYXJnaW4tbGVmdDphdXRvfQo8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5Pgo8aGVhZGVyPgogIDxoMT48aW1nIHNyYz0iL2Zhdmljb24uc3ZnIiB3aWR0aD0iMjIiIGhlaWdodD0iMjIiIHN0eWxlPSJ2ZXJ0aWNhbC1hbGlnbjotNHB4O21hcmdpbi1yaWdodDo2cHgiPkxpdmVDaGF0IEJhZC1SYXRpbmcgTW9uaXRvcjwvaDE+CiAgPGRpdiBjbGFzcz0iY2FsLXdyYXAiPgogICAgPGJ1dHRvbiBpZD0iZGF0ZUJ0biIgY2xhc3M9ImRhdGVidG4iPvCfk4UgPHNwYW4gaWQ9ImRhdGVMYWJlbCI+4oCUPC9zcGFuPjwvYnV0dG9uPgogICAgPGRpdiBpZD0iY2FsIiBjbGFzcz0iY2FsIGhpZGRlbiI+CiAgICAgIDxkaXYgY2xhc3M9ImNhbC1oZCI+PGJ1dHRvbiBpZD0iY2FsUHJldiI+4oC5PC9idXR0b24+PHNwYW4gaWQ9ImNhbFRpdGxlIj48L3NwYW4+PGJ1dHRvbiBpZD0iY2FsTmV4dCI+4oC6PC9idXR0b24+PC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9ImNhbC1ncmlkIiBpZD0iY2FsR3JpZCI+PC9kaXY+CiAgICA8L2Rpdj4KICA8L2Rpdj4KICA8YnV0dG9uIGNsYXNzPSJxIiBpZD0icXkiPuKXgCBZZXN0LjwvYnV0dG9uPgogIDxidXR0b24gY2xhc3M9InEiIGlkPSJxdCI+VG9kYXkg4pa2PC9idXR0b24+CiAgPHNlbGVjdCBpZD0iZ3JvdXAiPjxvcHRpb24gdmFsdWU9IiI+QWxsIGdyb3Vwczwvb3B0aW9uPjwvc2VsZWN0PgogIDxzZWxlY3QgaWQ9InR5cGUiPgogICAgPG9wdGlvbiB2YWx1ZT0iIj5BbGwgaXNzdWUgdHlwZXM8L29wdGlvbj4KICAgIDxvcHRpb24+RGVwb3NpdDwvb3B0aW9uPjxvcHRpb24+V2l0aGRyYXdhbDwvb3B0aW9uPjxvcHRpb24+T1RQPC9vcHRpb24+PG9wdGlvbj5HYW1lPC9vcHRpb24+CiAgICA8b3B0aW9uPlByb21vdGlvbnM8L29wdGlvbj48b3B0aW9uPkVtb3Rpb25hbDwvb3B0aW9uPjxvcHRpb24+QWNjb3VudDwvb3B0aW9uPjxvcHRpb24+U2lnbiB1cDwvb3B0aW9uPjxvcHRpb24+T3RoZXI8L29wdGlvbj4KICA8L3NlbGVjdD4KICA8bGFiZWwgY2xhc3M9ImNoayIgc3R5bGU9ImRpc3BsYXk6ZmxleDtnYXA6NnB4O2FsaWduLWl0ZW1zOmNlbnRlcjtjb2xvcjojOGJhMGM0O2ZvbnQtc2l6ZToxMi41cHgiPjxpbnB1dCB0eXBlPSJjaGVja2JveCIgaWQ9InJhdGVkb25seSIgY2hlY2tlZD4gT25seSByYXRlZDwvbGFiZWw+CiAgPGlucHV0IGlkPSJzZWFyY2giIHBsYWNlaG9sZGVyPSLwn5SOIHVzZXJuYW1lIG9yIGNoYXQgSUQiIC8+CiAgPGJ1dHRvbiBpZD0ibG9hZCIgY2xhc3M9InByaW1hcnkiPkxvYWQ8L2J1dHRvbj4KICA8YnV0dG9uIGlkPSJkbCI+4qyHIERvd25sb2FkPC9idXR0b24+CiAgPGJ1dHRvbiBpZD0ibG9nb3V0IiBjbGFzcz0icSI+TG9nb3V0PC9idXR0b24+CiAgPHNwYW4gaWQ9InN0YXR1cyI+4oCTPC9zcGFuPgo8L2hlYWRlcj4KPGRpdiBjbGFzcz0id3JhcCI+CiAgPGRpdiBjbGFzcz0iY2FyZHMiIGlkPSJjYXJkcyI+PC9kaXY+CiAgPGRpdiBjbGFzcz0idGFicyIgaWQ9InRhYnMiPjwvZGl2PgogIDxkaXYgaWQ9InN1bW1hcnkiPjwvZGl2PgogIDxkaXYgaWQ9InRhYmxld3JhcCI+PGRpdiBjbGFzcz0iZW1wdHkiPlBpY2sgYSBkYXRlIGFuZCBncm91cCwgdGhlbiBjbGljayBMb2FkLjwvZGl2PjwvZGl2Pgo8L2Rpdj4KPGRpdiBjbGFzcz0ibW9kYWwiIGlkPSJtb2RhbCI+PGRpdiBjbGFzcz0ic2hlZXQiPgogIDxkaXYgY2xhc3M9ImhkIj48YiBpZD0ibV90aXRsZSI+Q2hhdDwvYj48YSBpZD0ibV9vcGVuIiB0YXJnZXQ9Il9ibGFuayI+b3BlbiBpbiBMaXZlQ2hhdCDihpc8L2E+PGJ1dHRvbiBjbGFzcz0iY2xvc2UiIG9uY2xpY2s9ImNsb3NlQ2hhdCgpIj7inJUgQ2xvc2U8L2J1dHRvbj48L2Rpdj4KICA8ZGl2IGNsYXNzPSJiZCIgaWQ9Im1fYm9keSI+PC9kaXY+CjwvZGl2PjwvZGl2Pgo8c2NyaXB0PgpsZXQgR1JPVVBTPXt9LCBEQVRBPVtdLCB2aWV3PSJiYWQiLCBTRUFSQ0g9IiIsIFNFTF9EQVRFPW51bGwsIGNhbE1vbnRoPW51bGwsIGxvYWRpbmc9ZmFsc2U7CmNvbnN0ICQ9cz0+ZG9jdW1lbnQucXVlcnlTZWxlY3RvcihzKTsKY29uc3QgeW1kPWQ9PmAke2QuZ2V0RnVsbFllYXIoKX0tJHtTdHJpbmcoZC5nZXRNb250aCgpKzEpLnBhZFN0YXJ0KDIsJzAnKX0tJHtTdHJpbmcoZC5nZXREYXRlKCkpLnBhZFN0YXJ0KDIsJzAnKX1gOwpjb25zdCBsY0xpbms9aWQ9PmBodHRwczovL215LmxpdmVjaGF0aW5jLmNvbS9hcmNoaXZlcy8ke2lkfT9xdWVyeT0ke2lkfWA7CihmdW5jdGlvbigpe2NvbnN0IGQ9bmV3IERhdGUoKTtkLnNldERhdGUoZC5nZXREYXRlKCktMSk7U0VMX0RBVEU9eW1kKGQpO2RvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdkYXRlTGFiZWwnKS50ZXh0Q29udGVudD1TRUxfREFURTt9KSgpOwpjb25zdCBzZXRTdGF0dXM9dD0+JCgiI3N0YXR1cyIpLnRleHRDb250ZW50PXQ7CmZ1bmN0aW9uIHNldERhdGUodil7U0VMX0RBVEU9djtkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZGF0ZUxhYmVsJykudGV4dENvbnRlbnQ9djtjb25zdCBkPW5ldyBEYXRlKHYrJ1QwMDowMDowMCcpO2NhbE1vbnRoPW5ldyBEYXRlKGQuZ2V0RnVsbFllYXIoKSxkLmdldE1vbnRoKCksMSk7fQpmdW5jdGlvbiByZW5kZXJDYWwoKXtjb25zdCB5PWNhbE1vbnRoLmdldEZ1bGxZZWFyKCksbT1jYWxNb250aC5nZXRNb250aCgpOwogICQoIiNjYWxUaXRsZSIpLnRleHRDb250ZW50PWNhbE1vbnRoLnRvTG9jYWxlU3RyaW5nKCdlbicse21vbnRoOidsb25nJyx5ZWFyOidudW1lcmljJ30pOwogIGNvbnN0IHN0YXJ0RG93PW5ldyBEYXRlKHksbSwxKS5nZXREYXkoKSxkYXlzPW5ldyBEYXRlKHksbSsxLDApLmdldERhdGUoKSx0b2RheT15bWQobmV3IERhdGUoKSk7CiAgbGV0IGh0bWw9WydTJywnTScsJ1QnLCdXJywnVCcsJ0YnLCdTJ10ubWFwKGQ9PmA8ZGl2IGNsYXNzPSJkb3ciPiR7ZH08L2Rpdj5gKS5qb2luKCcnKTsKICBmb3IobGV0IGk9MDtpPHN0YXJ0RG93O2krKylodG1sKz0nPGRpdj48L2Rpdj4nOwogIGZvcihsZXQgZD0xO2Q8PWRheXM7ZCsrKXtjb25zdCBkcz1gJHt5fS0ke1N0cmluZyhtKzEpLnBhZFN0YXJ0KDIsJzAnKX0tJHtTdHJpbmcoZCkucGFkU3RhcnQoMiwnMCcpfWA7CiAgICBodG1sKz1gPGRpdiBjbGFzcz0iZGF5JHtkcz09PVNFTF9EQVRFPycgc2VsJzonJ30ke2RzPT09dG9kYXk/JyB0b2RheSc6Jyd9IiBkYXRhLWQ9IiR7ZHN9Ij4ke2R9PC9kaXY+YDt9CiAgJCgiI2NhbEdyaWQiKS5pbm5lckhUTUw9aHRtbDsKICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCcjY2FsR3JpZCAuZGF5JykuZm9yRWFjaChlbD0+ZWwub25jbGljaz0oKT0+e3NldERhdGUoZWwuZGF0YXNldC5kKTt0b2dnbGVDYWwoZmFsc2UpO2xvYWREYXRhKCk7fSk7fQpmdW5jdGlvbiB0b2dnbGVDYWwoc2hvdyl7Y29uc3QgYz0kKCIjY2FsIik7aWYoc2hvdyl7aWYoIWNhbE1vbnRoKXNldERhdGUoU0VMX0RBVEUpO3JlbmRlckNhbCgpO2MuY2xhc3NMaXN0LnJlbW92ZSgnaGlkZGVuJyk7fWVsc2UgYy5jbGFzc0xpc3QuYWRkKCdoaWRkZW4nKTt9CmRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJyxlPT57aWYoIWUudGFyZ2V0LmNsb3Nlc3QoJy5jYWwtd3JhcCcpJiYhZS50YXJnZXQuY2xvc2VzdCgnI2NhbCcpKXRvZ2dsZUNhbChmYWxzZSk7fSk7Cgphc3luYyBmdW5jdGlvbiBsb2FkR3JvdXBzKCl7R1JPVVBTPWF3YWl0KGF3YWl0IGZldGNoKCcvYXBpL2dyb3VwcycpKS5qc29uKCk7CiAgY29uc3Qgc2VsPSQoIiNncm91cCIpO09iamVjdC5lbnRyaWVzKEdST1VQUykuc29ydCgoYSxiKT0+KGFbMV18fCcnKS5sb2NhbGVDb21wYXJlKGJbMV18fCcnKSkuZm9yRWFjaCgoW2lkLG5dKT0+e2NvbnN0IG89ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnb3B0aW9uJyk7by52YWx1ZT1pZDtvLnRleHRDb250ZW50PWAke259ICgke2lkfSlgO3NlbC5hcHBlbmRDaGlsZChvKTt9KTt9CmNvbnN0IHJhdGVkPSgpPT4kKCIjcmF0ZWRvbmx5IikuY2hlY2tlZD8iMSI6IjAiOwphc3luYyBmdW5jdGlvbiBmZXRjaEdyb3VwKGdpZCl7Y29uc3QgdT1gL2FwaS9yZXBvcnQ/ZGF0ZT0ke1NFTF9EQVRFfSZncm91cD0ke2dpZH0mcmF0ZWQ9JHtyYXRlZCgpfWA7CiAgY29uc3Qgcj1hd2FpdCBmZXRjaCh1KTsgaWYoIXIub2spcmV0dXJuIFtdOyBjb25zdCBkPWF3YWl0IHIuanNvbigpOyByZXR1cm4gZC5yb3dzfHxbXTt9CmFzeW5jIGZ1bmN0aW9uIGxvYWREYXRhKCl7CiAgaWYobG9hZGluZylyZXR1cm47IGxvYWRpbmc9dHJ1ZTsKICBjb25zdCBnPSQoIiNncm91cCIpLnZhbHVlOwogIHRyeXsKICAgIGlmKGcpe3NldFN0YXR1cygibG9hZGluZyAiK2crIuKApiIpO0RBVEE9YXdhaXQgZmV0Y2hHcm91cChnKTt9CiAgICBlbHNle2NvbnN0IGlkcz1PYmplY3Qua2V5cyhHUk9VUFMpO0RBVEE9W107bGV0IGRvbmU9MDsKICAgICAgY29uc3QgUE9PTD01O2xldCBpZHg9MDsKICAgICAgYXdhaXQgbmV3IFByb21pc2UocmVzPT57bGV0IGFjdGl2ZT0wOwogICAgICAgIGNvbnN0IG5leHQ9KCk9PntpZihpZHg+PWlkcy5sZW5ndGgmJmFjdGl2ZT09PTApe3JlcygpO3JldHVybjt9CiAgICAgICAgICB3aGlsZShhY3RpdmU8UE9PTCYmaWR4PGlkcy5sZW5ndGgpe2NvbnN0IGdpZD1pZHNbaWR4KytdO2FjdGl2ZSsrOwogICAgICAgICAgICBmZXRjaEdyb3VwKGdpZCkudGhlbihyb3dzPT57REFUQT1EQVRBLmNvbmNhdChyb3dzKTt9KS5jYXRjaCgoKT0+e30pLmZpbmFsbHkoKCk9PnthY3RpdmUtLTtkb25lKys7c2V0U3RhdHVzKGBsb2FkaW5nIGFsbCBncm91cHPigKYgJHtkb25lfS8ke2lkcy5sZW5ndGh9YCk7bmV4dCgpO30pO30KICAgICAgICAgIGlmKGlkeD49aWRzLmxlbmd0aCYmYWN0aXZlPT09MClyZXMoKTt9OwogICAgICAgIG5leHQoKTt9KTsKICAgIH0KICAgIHNldFN0YXR1cygibG9hZGVkICIrREFUQS5sZW5ndGgrIiByYXRlZCByb3dzIik7CiAgfWNhdGNoKGUpe3NldFN0YXR1cygiZXJyb3I6ICIrZS5tZXNzYWdlKTt9CiAgbG9hZGluZz1mYWxzZTsgcmVuZGVyQWxsKCk7Cn0KZnVuY3Rpb24gY291bnRzKHJvd3MpewogIGNvbnN0IGJhZD1yb3dzLmZpbHRlcihyPT5yLnJhdGluZz09PSdiYWQnKSxnb29kPXJvd3MuZmlsdGVyKHI9PnIucmF0aW5nPT09J2dvb2QnKSx1bj1yb3dzLmZpbHRlcihyPT5yLnJhdGluZz09PSd1bnJhdGVkJyk7CiAgY29uc3QgdXI9e307dW4uZm9yRWFjaChyPT57aWYoci51bnJhdGVkX3JlYXNvbil1cltyLnVucmF0ZWRfcmVhc29uXT0odXJbci51bnJhdGVkX3JlYXNvbl18fDApKzE7fSk7CiAgcmV0dXJuIHt0b3RhbDpyb3dzLmxlbmd0aCxiYWQ6YmFkLmxlbmd0aCxnb29kOmdvb2QubGVuZ3RoLHVucmF0ZWQ6dW4ubGVuZ3RoLAogICAgYmFkX2FnZW50OmJhZC5maWx0ZXIocj0+ci5uX2FnZW50cz4wKS5sZW5ndGgsYmFkX2JvdDpiYWQuZmlsdGVyKHI9PnIubl9hZ2VudHM9PT0wKS5sZW5ndGgsCiAgICBiYWRfY29tbWVudGVkOmJhZC5maWx0ZXIocj0+ci5oYXNfY29tbWVudCkubGVuZ3RoLGdvb2RfY29tbWVudGVkOmdvb2QuZmlsdGVyKHI9PnIuaGFzX2NvbW1lbnQpLmxlbmd0aCx1bnJhdGVkX3JlYXNvbnM6dXJ9O30KZnVuY3Rpb24gc2NvcGVkKCl7Y29uc3QgdHk9JCgiI3R5cGUiKS52YWx1ZTtyZXR1cm4gdHk/REFUQS5maWx0ZXIocj0+ci5pc3N1ZV90eXBlPT09dHkpOkRBVEE7fQpjb25zdCBWSUVXUz17YWxsOnI9PnRydWUsYmFkOnI9PnIucmF0aW5nPT09J2JhZCcsYmFkX2FnZW50OnI9PnIucmF0aW5nPT09J2JhZCcmJnIubl9hZ2VudHM+MCxiYWRfYm90OnI9PnIucmF0aW5nPT09J2JhZCcmJnIubl9hZ2VudHM9PT0wLAogIGdvb2Q6cj0+ci5yYXRpbmc9PT0nZ29vZCcsdW5yYXRlZDpyPT5yLnJhdGluZz09PSd1bnJhdGVkJywKICByYXRlZF9jb21tZW50ZWQ6cj0+KHIucmF0aW5nPT09J2JhZCd8fHIucmF0aW5nPT09J2dvb2QnKSYmci5oYXNfY29tbWVudCxiYWRfY29tbWVudGVkOnI9PnIucmF0aW5nPT09J2JhZCcmJnIuaGFzX2NvbW1lbnQsZ29vZF9jb21tZW50ZWQ6cj0+ci5yYXRpbmc9PT0nZ29vZCcmJnIuaGFzX2NvbW1lbnR9OwpmdW5jdGlvbiByZW5kZXJBbGwoKXtjb25zdCByb3dzPXNjb3BlZCgpO2NvbnN0IGM9Y291bnRzKHJvd3MpOwogICQoIiNjYXJkcyIpLmlubmVySFRNTD1bWyJUb3RhbCIsYy50b3RhbF0sWyJCYWQiLGMuYmFkXSxbIkJhZCAoYWdlbnQpIixjLmJhZF9hZ2VudF0sWyJCYWQgKGJvdCBvbmx5KSIsYy5iYWRfYm90XSxbIkdvb2QiLGMuZ29vZF0sWyJVbnJhdGVkIixjLnVucmF0ZWRdLFsiQmFkICYgY29tbWVudGVkIixjLmJhZF9jb21tZW50ZWRdLFsiR29vZCAmIGNvbW1lbnRlZCIsYy5nb29kX2NvbW1lbnRlZF1dCiAgICAubWFwKChbbCxuXSk9PmA8ZGl2IGNsYXNzPSJjYXJkIj48ZGl2IGNsYXNzPSJuIj4ke259PC9kaXY+PGRpdiBjbGFzcz0ibCI+JHtsfTwvZGl2PjwvZGl2PmApLmpvaW4oJycpOwogIHJlbmRlclRhYnMoKTsgcmVuZGVyU3VtbWFyeShjKTsgcmVuZGVyVGFibGUocm93cyk7fQoKY29uc3QgVEFCUz1bWyJiYWQiLCJCYWQgKGFsbCkiXSxbImJhZF9hZ2VudCIsIkJhZCAoYWdlbnQpIl0sWyJiYWRfYm90IiwiQmFkIChib3Qgb25seSkiXSxbImdvb2QiLCJHb29kIHJhdGluZ3MiXSxbInVucmF0ZWQiLCJVbnJhdGVkIl0sWyJyYXRlZF9jb21tZW50ZWQiLCJSYXRlZCAmIGNvbW1lbnRlZCJdLFsiYmFkX2NvbW1lbnRlZCIsIkJhZCAmIGNvbW1lbnRlZCJdLFsiZ29vZF9jb21tZW50ZWQiLCJHb29kICYgY29tbWVudGVkIl0sWyJhbGwiLCJBbGwgY2hhdHMiXV07CmZ1bmN0aW9uIHJlbmRlclRhYnMoKXskKCIjdGFicyIpLmlubmVySFRNTD1UQUJTLm1hcCgoW2ssbF0pPT5gPGRpdiBjbGFzcz0idGFiICR7az09PXZpZXc/J2FjdGl2ZSc6Jyd9IiBkYXRhLWs9IiR7a30iPiR7bH08L2Rpdj5gKS5qb2luKCcnKTsKICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yQWxsKCcudGFiJykuZm9yRWFjaCh0PT50Lm9uY2xpY2s9KCk9Pnt2aWV3PXQuZGF0YXNldC5rO3JlbmRlckFsbCgpO30pO30KZnVuY3Rpb24gcmVuZGVyU3VtbWFyeShjKXtjb25zdCBlbD0kKCIjc3VtbWFyeSIpOwogIGlmKHZpZXc9PT0ndW5yYXRlZCcmJmMudW5yYXRlZF9yZWFzb25zJiZPYmplY3Qua2V5cyhjLnVucmF0ZWRfcmVhc29ucykubGVuZ3RoKXsKICAgIGNvbnN0IHJvd3M9T2JqZWN0LmVudHJpZXMoYy51bnJhdGVkX3JlYXNvbnMpLnNvcnQoKGEsYik9PmJbMV0tYVsxXSk7Y29uc3QgdG90PXJvd3MucmVkdWNlKChzLFssdl0pPT5zK3YsMCl8fDE7CiAgICBlbC5pbm5lckhUTUw9JzxkaXYgY2xhc3M9Im5vdGUiPjxiPldoeSB0aGVzZSBjaGF0cyBhcmUgdW5yYXRlZDwvYj48dGFibGU+Jytyb3dzLm1hcCgoW2ssdl0pPT5gPHRyPjx0ZD48Yj4ke3Z9PC9iPjwvdGQ+PHRkPiR7KHYvdG90KjEwMCkudG9GaXhlZCgxKX0lPC90ZD48dGQ+JHtrfTwvdGQ+PC90cj5gKS5qb2luKCcnKSsnPC90YWJsZT48L2Rpdj4nOwogIH0gZWxzZSBlbC5pbm5lckhUTUw9Jyc7fQpjb25zdCByYj1yPT5yPT09J2JhZCc/JzxzcGFuIGNsYXNzPSJiYWRnZSBiYWQiPkJBRDwvc3Bhbj4nOnI9PT0nZ29vZCc/JzxzcGFuIGNsYXNzPSJiYWRnZSBnb29kIj5HT09EPC9zcGFuPic6JzxzcGFuIGNsYXNzPSJiYWRnZSB1biI+4oCUPC9zcGFuPic7CmZ1bmN0aW9uIHJlbmRlclRhYmxlKHJvd3MpewogIGxldCBzZWw9cm93cy5maWx0ZXIoVklFV1Nbdmlld118fFZJRVdTLmJhZCk7CiAgc2VsPXNlbC5maWx0ZXIocj0+IVNFQVJDSHx8KHIuY3VzdG9tZXJ8fCcnKS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKFNFQVJDSCl8fChyLmNoYXRfaWR8fCcnKS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKFNFQVJDSCkpOwogIGNvbnN0IHBlckFnZW50PXZpZXc9PT0nYmFkJ3x8dmlldz09PSdiYWRfYWdlbnQnOwogIGxldCBmbGF0PVtdOwogIGlmKHBlckFnZW50KXtzZWwuZm9yRWFjaChyPT57aWYoci5hZ2VudHMmJnIuYWdlbnRzLmxlbmd0aClyLmFnZW50cy5mb3JFYWNoKGE9PmZsYXQucHVzaChbcixhLm5hbWVdKSk7ZWxzZSBmbGF0LnB1c2goW3IsJyddKTt9KTt9CiAgZWxzZSBmbGF0PXNlbC5tYXAocj0+W3IsKHIuYWdlbnRzfHxbXSkubWFwKGE9PmEubmFtZSkuam9pbignLCAnKV0pOwogIGlmKCFmbGF0Lmxlbmd0aCl7JCgiI3RhYmxld3JhcCIpLmlubmVySFRNTD0nPGRpdiBjbGFzcz0iZW1wdHkiPicrKFNFQVJDSD8nTm8gbWF0Y2guJzonTm8gcm93cy4nKSsnPC9kaXY+JztyZXR1cm47fQogIGNvbnN0IGhlYWQ9YDx0cj48dGg+VGltZTwvdGg+PHRoPkdyb3VwPC90aD48dGg+SUQ8L3RoPjx0aD5DaGF0PC90aD48dGg+Q3VzdG9tZXI8L3RoPjx0aD5SYXRpbmc8L3RoPjx0aD5Jc3N1ZTwvdGg+PHRoPiR7cGVyQWdlbnQ/J0FnZW50JzonQWdlbnRzJ308L3RoPjx0aD5Cb3Q8L3RoPjx0aD5SZWFzb24gLyBDbGFzczwvdGg+PHRoPlByb2JsZW08L3RoPjwvdHI+YDsKICBjb25zdCBib2R5PWZsYXQubWFwKChbcixhbl0pPT57Y29uc3Qgc2hhcmVkPXIubl9hZ2VudHM+MTsKICAgIGNvbnN0IG5hbWVzPShyLmFnZW50c3x8W10pLm1hcChhPT5hLm5hbWUpLmZpbHRlcihCb29sZWFuKS5qb2luKCcsICcpOwogICAgY29uc3Qgc2hhcmU9c2hhcmVkP2AgPGEgY2xhc3M9ImJhZGdlIGJhZCIgc3R5bGU9ImN1cnNvcjpwb2ludGVyIiB0aXRsZT0iQWdlbnRzIGludm9sdmVkOiAke25hbWVzfSIgb25jbGljaz0ib3BlbkNoYXQoJyR7ci5jaGF0X2lkfScpIj5TSEFSRUQgw5cke3Iubl9hZ2VudHN9IOKGlzwvYT5gOicnOwogICAgY29uc3QgYm90cz0oci5ib3RzfHxbXSkuam9pbignLCAnKXx8KHIubl9hZ2VudHM9PT0wPyc8c3BhbiBjbGFzcz0iYmFkZ2UgYmFkIj5CT1QgT05MWTwvc3Bhbj4nOicnKTsKICAgIHJldHVybiBgPHRyIGNsYXNzPSIke3NoYXJlZD8nc2hhcmVkJzonJ30iPjx0ZD4ke3IudGltZXx8Jyd9PC90ZD48dGQ+JHtyLmdyb3VwX25hbWV8fCcnfTwvdGQ+PHRkPiR7ci5ncm91cF9pZD8/Jyd9PC90ZD4KICAgICAgPHRkPjxhIG9uY2xpY2s9Im9wZW5DaGF0KCcke3IuY2hhdF9pZH0nKSI+JHtyLmNoYXRfaWR9PC9hPjxhIGNsYXNzPSJleHQiIGhyZWY9IiR7bGNMaW5rKHIuY2hhdF9pZCl9IiB0YXJnZXQ9Il9ibGFuayI+4oaXPC9hPjwvdGQ+CiAgICAgIDx0ZD4ke3IuY3VzdG9tZXJ8fCcnfTwvdGQ+PHRkPiR7cmIoci5yYXRpbmcpfSAke3IuaGFzX2NvbW1lbnQ/J/CfkqwnOicnfTwvdGQ+PHRkPiR7ci5pc3N1ZV90eXBlfHwnJ308L3RkPgogICAgICA8dGQ+JHtwZXJBZ2VudD9hbjooci5hZ2VudHN8fFtdKS5tYXAoYT0+YS5uYW1lKS5qb2luKCcsICcpfSR7c2hhcmV9PC90ZD48dGQ+JHtib3RzfTwvdGQ+CiAgICAgIDx0ZD4ke3IucmF0aW5nPT09J3VucmF0ZWQnPyhyLnVucmF0ZWRfcmVhc29ufHwnJyk6KHIuY2xhc3NpZmljYXRpb258fFtdKS5qb2luKCcsICcpfTwvdGQ+CiAgICAgIDx0ZCBjbGFzcz0ibXV0ZWQiPiR7KHIucHJvYmxlbXx8JycpLnNsaWNlKDAsMTIwKX08L3RkPjwvdHI+YDt9KS5qb2luKCcnKTsKICAkKCIjdGFibGV3cmFwIikuaW5uZXJIVE1MPWA8dGFibGU+JHtoZWFkfSR7Ym9keX08L3RhYmxlPmA7fQpmdW5jdGlvbiBvcGVuQ2hhdChpZCl7Y29uc3Qgcj1EQVRBLmZpbmQoeD0+eC5jaGF0X2lkPT09aWQpO2lmKCFyKXJldHVybjsKICAkKCIjbW9kYWwiKS5jbGFzc0xpc3QuYWRkKCdvbicpOyQoIiNtX3RpdGxlIikudGV4dENvbnRlbnQ9YENoYXQgJHtyLmNoYXRfaWR9IMK3ICR7ci5ncm91cF9uYW1lfSAoJHtyLmdyb3VwX2lkfSkgwrcgJHtyLnRpbWV9YDsKICAkKCIjbV9vcGVuIikuaHJlZj1sY0xpbmsoci5jaGF0X2lkKTsKICBjb25zdCByZXY9YDxkaXYgY2xhc3M9InJldiI+CiAgICA8ZGl2IGNsYXNzPSJzZWMtaCI+8J+TnSBDaGF0IFN1bW1hcnk8L2Rpdj4KICAgIDxkaXYgY2xhc3M9Imt2Ij48c3BhbiBjbGFzcz0iayI+Q3VzdG9tZXI8L3NwYW4+IDxiPiR7ci5jdXN0b21lcn08L2I+PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJrdiI+PHNwYW4gY2xhc3M9ImsiPkdyb3VwPC9zcGFuPiAke3IuZ3JvdXBfbmFtZX0gKCR7ci5ncm91cF9pZH0pPC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJrdiI+PHNwYW4gY2xhc3M9ImsiPlRpbWU8L3NwYW4+ICR7ci50aW1lfHwnJ308L2Rpdj4KICAgIDxkaXYgY2xhc3M9Imt2Ij48c3BhbiBjbGFzcz0iayI+UmF0aW5nPC9zcGFuPiAke3JiKHIucmF0aW5nKX0gJHtyLnJhdGluZ19sYWJlbHx8Jyd9ICR7ci5oYXNfY29tbWVudD8n8J+SrCc6Jyd9PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJrdiI+PHNwYW4gY2xhc3M9ImsiPklzc3VlIFR5cGU8L3NwYW4+IDxiPiR7ci5pc3N1ZV90eXBlfHwn4oCUJ308L2I+JHtyLmNvbmNlcm4/YCA8c3BhbiBjbGFzcz0ibXV0ZWQiPihmb3JtOiAke3IuY29uY2Vybn0pPC9zcGFuPmA6Jyd9PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJrdiI+PHNwYW4gY2xhc3M9ImsiPkFnZW50czwvc3Bhbj4gJHsoci5hZ2VudHN8fFtdKS5tYXAoYT0+YS5uYW1lKS5qb2luKCcsICcpfHwn4oCUJ30gJHtyLm5fYWdlbnRzPjE/YDxzcGFuIGNsYXNzPSJiYWRnZSBiYWQiPlNIQVJFRCDDlyR7ci5uX2FnZW50c308L3NwYW4+YDonJ308L2Rpdj4KICAgIDxkaXYgY2xhc3M9Imt2Ij48c3BhbiBjbGFzcz0iayI+Qm90KHMpPC9zcGFuPiAkeyhyLmJvdHN8fFtdKS5qb2luKCcsICcpfHwoci5uX2FnZW50cz09PTA/JzxzcGFuIGNsYXNzPSJiYWRnZSBiYWQiPkJPVCBPTkxZPC9zcGFuPic6J+KAlCcpfTwvZGl2PgogICAgPGRpdiBjbGFzcz0ic2VjLWgiPvCflI4gQ2hhdCBSZXZpZXc8L2Rpdj4KICAgIDxkaXYgY2xhc3M9Imt2Ij48c3BhbiBjbGFzcz0iayI+UHJvYmxlbTwvc3Bhbj4gJHtyLnByb2JsZW18fCfigJQnfTwvZGl2PgogICAgPGRpdiBjbGFzcz0ia3YiPjxzcGFuIGNsYXNzPSJrIj5FcnJvciAvIFJvb3QgY2F1c2U8L3NwYW4+ICR7ci5lcnJvcnx8J+KAlCd9PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJrdiI+PHNwYW4gY2xhc3M9ImsiPkNsYXNzaWZpY2F0aW9uPC9zcGFuPiAkeyhyLmNsYXNzaWZpY2F0aW9ufHxbXSkuam9pbignLCAnKXx8KHIucmF0aW5nPT09J3VucmF0ZWQnPygndW5yYXRlZDogJysoci51bnJhdGVkX3JlYXNvbnx8JycpKTon4oCUJyl9PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJzZWMtaCI+4pyFIENoYXQgU29sdXRpb248L2Rpdj4KICAgIDxkaXYgY2xhc3M9Imt2Ij4ke3Iuc3VnZ2VzdGlvbnx8J+KAlCd9PC9kaXY+PC9kaXY+YDsKICBjb25zdCB0cj0oci50cmFuc2NyaXB0fHxbXSkubWFwKG09PmA8ZGl2IGNsYXNzPSJtc2cgJHttLnJvbGV9Ij48c3BhbiBjbGFzcz0id2hvIj4ke20ubmFtZXx8bS5yb2xlfTwvc3Bhbj48c3BhbiBjbGFzcz0idG0iPiR7bS50fHwnJ308L3NwYW4+PHNwYW4+JHsobS50ZXh0fHwnJykucmVwbGFjZSgvPC9nLCcmbHQ7Jyl9PC9zcGFuPjwvZGl2PmApLmpvaW4oJycpOwogICQoIiNtX2JvZHkiKS5pbm5lckhUTUw9cmV2K2A8ZGl2IGNsYXNzPSJ0ciI+JHt0cnx8JzxkaXYgY2xhc3M9ImVtcHR5Ij5ObyBtZXNzYWdlczwvZGl2Pid9PC9kaXY+YDt9CmZ1bmN0aW9uIGNsb3NlQ2hhdCgpeyQoIiNtb2RhbCIpLmNsYXNzTGlzdC5yZW1vdmUoJ29uJyk7fQpmdW5jdGlvbiBkb3dubG9hZCgpe2xldCBzZWw9c2NvcGVkKCkuZmlsdGVyKFZJRVdTW3ZpZXddfHxWSUVXUy5iYWQpOwogIGNvbnN0IEg9WyJUaW1lIiwiR3JvdXAiLCJHcm91cCBJRCIsIkNoYXQgSUQiLCJMaW5rIiwiQ3VzdG9tZXIiLCJSYXRpbmciLCJJc3N1ZSIsIkFnZW50cyIsIkJvdCIsIkNsYXNzaWZpY2F0aW9uIiwiUHJvYmxlbSIsIkVycm9yIiwiU29sdXRpb24iXTsKICBjb25zdCBxPXY9PiciJytTdHJpbmcodj09bnVsbD8nJzp2KS5yZXBsYWNlKC8iL2csJyIiJykrJyInOwogIGNvbnN0IGxpbmVzPVtILm1hcChxKS5qb2luKCcsJyldOwogIHNlbC5mb3JFYWNoKHI9PmxpbmVzLnB1c2goW3IudGltZSxyLmdyb3VwX25hbWUsci5ncm91cF9pZCxyLmNoYXRfaWQsbGNMaW5rKHIuY2hhdF9pZCksci5jdXN0b21lcixyLnJhdGluZyxyLmlzc3VlX3R5cGUsCiAgICAoci5hZ2VudHN8fFtdKS5tYXAoYT0+YS5uYW1lKS5qb2luKCc7ICcpLChyLmJvdHN8fFtdKS5qb2luKCc7ICcpLChyLmNsYXNzaWZpY2F0aW9ufHxbXSkuam9pbignOyAnKSxyLnByb2JsZW0sci5lcnJvcixyLnN1Z2dlc3Rpb25dLm1hcChxKS5qb2luKCcsJykpKTsKICBjb25zdCBibG9iPW5ldyBCbG9iKFsiXHVmZWZmIitsaW5lcy5qb2luKCJcclxuIildLHt0eXBlOid0ZXh0L2NzdjtjaGFyc2V0PXV0Zi04J30pOwogIGNvbnN0IGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnYScpO2EuaHJlZj1VUkwuY3JlYXRlT2JqZWN0VVJMKGJsb2IpO2EuZG93bmxvYWQ9YExpdmVDaGF0XyR7dmlld31fJHtTRUxfREFURX0uY3N2YDthLmNsaWNrKCk7fQokKCIjbG9hZCIpLm9uY2xpY2s9bG9hZERhdGE7CiQoIiNkbCIpLm9uY2xpY2s9ZG93bmxvYWQ7CiQoIiNncm91cCIpLm9uY2hhbmdlPWxvYWREYXRhOyQoIiN0eXBlIikub25jaGFuZ2U9cmVuZGVyQWxsOyQoIiNyYXRlZG9ubHkiKS5vbmNoYW5nZT1sb2FkRGF0YTsKJCgiI2RhdGVCdG4iKS5vbmNsaWNrPWU9PntlLnN0b3BQcm9wYWdhdGlvbigpO3RvZ2dsZUNhbCgkKCIjY2FsIikuY2xhc3NMaXN0LmNvbnRhaW5zKCdoaWRkZW4nKSk7fTsKJCgiI2NhbFByZXYiKS5vbmNsaWNrPWU9PntlLnN0b3BQcm9wYWdhdGlvbigpO2NhbE1vbnRoLnNldE1vbnRoKGNhbE1vbnRoLmdldE1vbnRoKCktMSk7cmVuZGVyQ2FsKCk7fTsKJCgiI2NhbE5leHQiKS5vbmNsaWNrPWU9PntlLnN0b3BQcm9wYWdhdGlvbigpO2NhbE1vbnRoLnNldE1vbnRoKGNhbE1vbnRoLmdldE1vbnRoKCkrMSk7cmVuZGVyQ2FsKCk7fTsKJCgiI3F5Iikub25jbGljaz0oKT0+e2NvbnN0IGQ9bmV3IERhdGUoKTtkLnNldERhdGUoZC5nZXREYXRlKCktMSk7c2V0RGF0ZSh5bWQoZCkpO2xvYWREYXRhKCk7fTsKJCgiI3F0Iikub25jbGljaz0oKT0+e2NvbnN0IGQ9bmV3IERhdGUoKTtzZXREYXRlKHltZChkKSk7bG9hZERhdGEoKTt9OwokKCIjc2VhcmNoIikub25pbnB1dD1lPT57U0VBUkNIPWUudGFyZ2V0LnZhbHVlLnRyaW0oKS50b0xvd2VyQ2FzZSgpO3JlbmRlckFsbCgpO307CiQoIiNsb2dvdXQiKS5vbmNsaWNrPWFzeW5jKCk9Pnt0cnl7YXdhaXQgZmV0Y2goJy9hcGkvbG9nb3V0Jyx7bWV0aG9kOidQT1NUJ30pO31jYXRjaChlKXt9bG9jYXRpb24uaHJlZj0nLyc7fTsKbG9hZEdyb3VwcygpOwo8L3NjcmlwdD4KPC9ib2R5Pgo8L2h0bWw+Cg==";
const LOGIN_HTML_B64 = "PCFkb2N0eXBlIGh0bWw+PGh0bWwgbGFuZz0iZW4iPjxoZWFkPjxtZXRhIGNoYXJzZXQ9InV0Zi04Ii8+CjxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSIvPgo8dGl0bGU+TGl2ZUNoYXQgQmFkLVJhdGluZyBNb25pdG9yPC90aXRsZT4KPGxpbmsgcmVsPSJpY29uIiB0eXBlPSJpbWFnZS9zdmcreG1sIiBocmVmPSIvZmF2aWNvbi5zdmciLz4KPHN0eWxlPgoqe2JveC1zaXppbmc6Ym9yZGVyLWJveH0KYm9keXttYXJnaW46MDtoZWlnaHQ6MTAwdmg7ZGlzcGxheTpmbGV4O2FsaWduLWl0ZW1zOmNlbnRlcjtqdXN0aWZ5LWNvbnRlbnQ6Y2VudGVyO2ZvbnQ6MTRweC8xLjUgc3lzdGVtLXVpLFNlZ29lIFVJLFJvYm90byxBcmlhbDtjb2xvcjojZTdlZWZjOwogYmFja2dyb3VuZDpyYWRpYWwtZ3JhZGllbnQoMTIwMHB4IDYwMHB4IGF0IDIwJSAtMTAlLCMxYjJiNTIsdHJhbnNwYXJlbnQgNjAlKSxsaW5lYXItZ3JhZGllbnQoMTgwZGVnLCMwYjE0MjYsIzBhMTEyMCl9Ci5ib3h7d2lkdGg6MzQwcHg7cGFkZGluZzoyNnB4O2JvcmRlci1yYWRpdXM6MTZweDtiYWNrZ3JvdW5kOmxpbmVhci1ncmFkaWVudCgxNjBkZWcscmdiYSg1OSwxMzAsMjQ2LC4xNCkscmdiYSgxMzksOTIsMjQ2LC4wNikpLCMxMTFjMzM7Ym9yZGVyOjFweCBzb2xpZCAjMmIzZjYzO2JveC1zaGFkb3c6MCAzMHB4IDYwcHggLTMwcHggIzAwMH0KaDF7Zm9udC1zaXplOjE3cHg7bWFyZ2luOjAgMCA0cHh9cC5zdWJ7Y29sb3I6IzhiYTBjNDttYXJnaW46MCAwIDE2cHg7Zm9udC1zaXplOjEyLjVweH0KbGFiZWx7ZGlzcGxheTpibG9jaztjb2xvcjojOGJhMGM0O2ZvbnQtc2l6ZToxMnB4O21hcmdpbjoxMHB4IDAgNHB4fQppbnB1dHt3aWR0aDoxMDAlO3BhZGRpbmc6MTBweCAxMnB4O2JvcmRlci1yYWRpdXM6MTBweDtib3JkZXI6MXB4IHNvbGlkICMyMjMwNGQ7YmFja2dyb3VuZDojMGIxNDI2O2NvbG9yOiNlN2VlZmN9CmJ1dHRvbnt3aWR0aDoxMDAlO21hcmdpbi10b3A6MTZweDtwYWRkaW5nOjExcHg7Ym9yZGVyOjA7Ym9yZGVyLXJhZGl1czoxMHB4O2ZvbnQtd2VpZ2h0OjcwMDtjb2xvcjojZmZmO2N1cnNvcjpwb2ludGVyO2JhY2tncm91bmQ6bGluZWFyLWdyYWRpZW50KDEzNWRlZywjM2I4MmY2LCMwNmI2ZDQpfQouZXJye2NvbG9yOiNmZjVkNmM7Zm9udC1zaXplOjEyLjVweDttYXJnaW4tdG9wOjEwcHg7bWluLWhlaWdodDoxNnB4fQo8L3N0eWxlPjwvaGVhZD48Ym9keT4KPGZvcm0gY2xhc3M9ImJveCIgb25zdWJtaXQ9InJldHVybiBkb0xvZ2luKGV2ZW50KSI+CjxoMT5MaXZlQ2hhdCBCYWQtUmF0aW5nIE1vbml0b3I8L2gxPjxwIGNsYXNzPSJzdWIiPlNpZ24gaW4gdG8gY29udGludWU8L3A+CjxsYWJlbD5Vc2VybmFtZTwvbGFiZWw+PGlucHV0IGlkPSJ1IiBhdXRvY29tcGxldGU9InVzZXJuYW1lIiBhdXRvZm9jdXMvPgo8bGFiZWw+UGFzc3dvcmQ8L2xhYmVsPjxpbnB1dCBpZD0icCIgdHlwZT0icGFzc3dvcmQiIGF1dG9jb21wbGV0ZT0iY3VycmVudC1wYXNzd29yZCIvPgo8YnV0dG9uIHR5cGU9InN1Ym1pdCI+U2lnbiBpbjwvYnV0dG9uPjxkaXYgY2xhc3M9ImVyciIgaWQ9ImVyciI+PC9kaXY+CjwvZm9ybT4KPHNjcmlwdD4KYXN5bmMgZnVuY3Rpb24gZG9Mb2dpbihlKXtlLnByZXZlbnREZWZhdWx0KCk7ZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2VycicpLnRleHRDb250ZW50PScnOwogY29uc3Qgcj1hd2FpdCBmZXRjaCgnL2FwaS9sb2dpbicse21ldGhvZDonUE9TVCcsaGVhZGVyczp7J0NvbnRlbnQtVHlwZSc6J2FwcGxpY2F0aW9uL2pzb24nfSxib2R5OkpTT04uc3RyaW5naWZ5KHt1c2VyOnUudmFsdWUscGFzczpwLnZhbHVlfSl9KTsKIGlmKHIub2spe2xvY2F0aW9uLmhyZWY9Jy8nO31lbHNle2NvbnN0IGQ9YXdhaXQgci5qc29uKCkuY2F0Y2goKCk9Pih7fSkpO2RvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdlcnInKS50ZXh0Q29udGVudD1kLmVycm9yfHwnTG9naW4gZmFpbGVkJzt9CiByZXR1cm4gZmFsc2U7fQo8L3NjcmlwdD48L2JvZHk+PC9odG1sPgo=";
const FAVICON_B64 = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+CiAgPGRlZnM+CiAgICA8bGluZWFyR3JhZGllbnQgaWQ9ImciIHgxPSIwIiB5MT0iMCIgeDI9IjEiIHkyPSIxIj4KICAgICAgPHN0b3Agb2Zmc2V0PSIwIiBzdG9wLWNvbG9yPSIjM2I4MmY2Ii8+CiAgICAgIDxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iIzA2YjZkNCIvPgogICAgPC9saW5lYXJHcmFkaWVudD4KICA8L2RlZnM+CiAgPHJlY3QgeD0iMiIgeT0iMiIgd2lkdGg9IjYwIiBoZWlnaHQ9IjYwIiByeD0iMTYiIGZpbGw9InVybCgjZykiLz4KICA8cGF0aCBkPSJNMTggMTVoMjhhNiA2IDAgMCAxIDYgNnYxM2E2IDYgMCAwIDEtNiA2SDMwbC05IDh2LThoLTNhNiA2IDAgMCAxLTYtNlYyMWE2IDYgMCAwIDEgNi02eiIgZmlsbD0iI2ZmZmZmZiIvPgogIDxjaXJjbGUgY3g9IjI0IiBjeT0iMjgiIHI9IjIuNyIgZmlsbD0iIzI1NjNlYiIvPgogIDxjaXJjbGUgY3g9IjMyIiBjeT0iMjgiIHI9IjIuNyIgZmlsbD0iIzI1NjNlYiIvPgogIDxjaXJjbGUgY3g9IjQwIiBjeT0iMjgiIHI9IjIuNyIgZmlsbD0iIzI1NjNlYiIvPgogIDxjaXJjbGUgY3g9IjUxIiBjeT0iMTMiIHI9IjguNSIgZmlsbD0iI2VmNDQ0NCIgc3Ryb2tlPSIjMGIxNDI2IiBzdHJva2Utd2lkdGg9IjIiLz4KICA8cmVjdCB4PSI0OS45IiB5PSI4LjQiIHdpZHRoPSIyLjIiIGhlaWdodD0iNiIgcng9IjEuMSIgZmlsbD0iI2ZmZmZmZiIvPgogIDxjaXJjbGUgY3g9IjUxIiBjeT0iMTcuNCIgcj0iMS4zIiBmaWxsPSIjZmZmZmZmIi8+Cjwvc3ZnPgo=";
// LiveChat Bad-Rating Monitor - Cloudflare Worker
const PH = 8;
const LC_API = "https://api.livechatinc.com/v3.5/agent/action/";
const LC_CFG = "https://api.livechatinc.com/v3.5/configuration/action/";
const SESSION_HOURS = 12;
const MAX_PAGES = 45;

const PROFANITY = ["putang","puta","gago","gaga","tanga","bobo","ulol","hayop","hayup","lintik","tarantado","punyeta","kingina","kupal","inutil","buraot","sakim","lintek","burat","pokpok","ina mo","fuck","shit","bitch","asshole","bastard","stupid","idiot","damn","wtf","dumbass","moron"];
const SIGNAL_WORDS = ["scam","fraud","refund","magnanakaw","steal","rob"];
const HOLD_PAT = ["please wait","for a while","wait for","submitted to the relevant","escalat","still working","be patient","kindly wait","give me a moment","bear with me","checking","under review","please hold","one moment"];
const CUST_ERRORS = [
  [["abnormal betting","unusual betting","irregular betting","winning amount","deduct","suspicious bet","betting pattern"],
   "Withdrawal rejected for abnormal/unusual betting; winnings deducted",
   "Show the customer the evidence and the appeal path; escalate to Risk; apply one consistent deduction SOP."],
  [["deposit","deposito","not credited","not reflect","hindi pumasok","hindi naipasok","stuck","naipit","pending deposit","load","top up","recharge"],
   "Deposit not credited / stuck (GCash/PSP delay)",
   "Check the PSP/GCash status and the receipt; credit or refund within SLA; give a ticket/ETA instead of 'wait'."],
  [["withdraw","withdrawal","payout","cash out","cashout","encash","widraw"],
   "Withdrawal pending / not received", "Verify the account and processing status; give a clear status or ETA."],
  [["otp","verification code","sim","mobile number","registered number","unbind","change number","cannot receive code"],
   "OTP not received / cannot change registered number (e.g., lost SIM)",
   "Apply the lost-SIM / change-number exception flow; don't dead-end the customer."],
  [["bonus","turnover","promo","free spin","scatter","rebate","cashback"],
   "Bonus / turnover / promotion terms confusion", "Explain the turnover/promo terms clearly and verify eligibility."],
  [["locked","frozen","cannot log","can't log","cannot login","password","forgot user","account lock"],
   "Account access / locked out", "Walk through the verification & unlock steps once, then unlock or escalate; avoid repeating requirements."],
  [["error","glitch","maintenance","lag","disconnect","stuck","server"],
   "Game error / technical glitch", "Check the server logs and confirm with the technical team; inform the customer of the outcome."],
];

function has(t, arr){ t=(t||"").toLowerCase(); return arr.some(w=>t.includes(w)); }
function b64url(bytes){ let s=""; const b=new Uint8Array(bytes); for(let i=0;i<b.length;i++) s+=String.fromCharCode(b[i]); return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,""); }
function b64urlDecode(str){ str=str.replace(/-/g,"+").replace(/_/g,"/"); str += "=".repeat((4 - str.length % 4) % 4); const bin=atob(str); const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)); return new TextDecoder().decode(bytes); }
function b64toUtf8(b64){ const bin=atob(b64); const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)); return new TextDecoder().decode(bytes); }

async function hmacHex(secret, msg){
  const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), {name:"HMAC",hash:"SHA-256"}, false, ["sign"]);
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(msg));
  return b64url(sig);
}
async function makeSession(user, secret){
  const p = b64url(new TextEncoder().encode(JSON.stringify({u:user, e:Math.floor(Date.now()/1000)+SESSION_HOURS*3600})));
  return p + "." + await hmacHex(secret, p);
}
async function verifySession(tok, secret){
  try{
    const [p, sig] = tok.split(".");
    const exp = await hmacHex(secret, p);
    if(exp !== sig) return null;
    const data = JSON.parse(b64urlDecode(p));
    if(data.e < Math.floor(Date.now()/1000)) return null;
    return data.u;
  }catch(e){ return null; }
}
function getCookie(req){ const c=req.headers.get("Cookie")||""; const m=c.match(/(?:^|;\s*)lcmon=([^;]+)/); return m?m[1]:null; }
async function getUser(req, env){ const t=getCookie(req); return t? await verifySession(t, env.SESSION_SECRET):null; }
function json(obj, status=200){ return new Response(JSON.stringify(obj), {status, headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}}); }
function html(str){ return new Response(str, {headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}}); }

function iso6(d){ return d.toISOString().slice(0,19)+".000000+00:00"; }
function dayRange(dateStr){
  const start = Date.parse(dateStr+"T00:00:00.000+08:00");
  return { from: iso6(new Date(start)), to: iso6(new Date(start+86400000)) };
}
function pht(iso){ if(!iso) return null; const d=new Date(iso); return new Date(d.getTime()+PH*3600000); }
function fmtDT(d){ return d? d.toISOString().slice(0,10)+" "+d.toISOString().slice(11,16) : ""; }
function fmtT(d){ return d? d.toISOString().slice(11,19) : ""; }

async function lcPost(env, url, body){
  return fetch(url, { method:"POST", headers:{ "Authorization":"Basic "+env.LIVECHAT_TOKEN, "Content-Type":"application/json" }, body: JSON.stringify(body) });
}
async function getGroups(env){
  if(env.LC_KV){ const cached = await env.LC_KV.get("groups", "json"); if(cached) return cached; }
  const r = await lcPost(env, LC_CFG+"list_groups", { all:true });
  if(!r.ok) return {};
  const arr = await r.json();
  const map = {};
  for(const g of arr) map[g.id] = g.name;
  if(env.LC_KV) await env.LC_KV.put("groups", JSON.stringify(map), { expirationTtl: 604800 });
  return map;
}

function classify(cust, human, rating){
  const labels=[];
  const jc=cust.join(" ").toLowerCase();
  if(has(jc, PROFANITY)) labels.push("Cursing/Profanity");
  if(!human.length){ labels.push("No reply"); if(cust.length) labels.push("Abandonment"); }
  else{
    const hold = human.filter(a=>has(a, HOLD_PAT)).length;
    if(hold && hold>=Math.max(1, human.length*0.6) && rating==="bad") labels.push("No solution provided");
  }
  if(has(human.join(" ").toLowerCase(), ["cannot help","not possible","create a new account","cannot unlock","we cannot","unable to","walang magagawa"]) && rating==="bad") labels.push("Possible agent mistake (review)");
  if(has(jc, SIGNAL_WORDS)) labels.push("Claimed scam/fraud");
  return labels;
}
function issueType(concern, labels, cust){
  const jc=cust.join(" ").toLowerCase(), c=(concern||"").toLowerCase();
  if(jc.includes("otp")||jc.includes("verification code")||c.includes("otp")) return "OTP";
  const m={"withdrawal":"Withdrawal","deposit":"Deposit","promotions":"Promotions","game issue":"Game","game":"Game","sign up":"Sign up","forget password":"Account"};
  for(const k in m){ if(c.includes(k)) return m[k]; }
  if(labels.includes("Cursing/Profanity")) return "Emotional";
  return "Other";
}
function detectError(cust, human, labels){
  const c=cust.join(" ").toLowerCase();
  for(const [kws,err,sol] of CUST_ERRORS){ if(kws.some(k=>c.includes(k))) return [err,sol]; }
  if(labels.includes("No reply")) return ["No human agent ever replied (bot-only)", "Review routing/staffing and call the customer back."];
  if(labels.includes("No solution provided")) return ["Agent gave only holding replies - no resolution", "Escalate to an agent with authority; give an ETA or an actual resolution."];
  if(labels.includes("Cursing/Profanity")) return ["Customer emotional/abusive (no specific request)", "Assign a senior agent to de-escalate; check account/betting status."];
  return ["No specific issue detected in the transcript", "Review the transcript and follow up as needed."];
}
function summarize(cust){ if(!cust.length) return ""; return cust.reduce((a,b)=>b.length>a.length?b:a,"").slice(0,240); }

function buildRow(c, groups){
  const t=c.thread||{}, users=c.users||[];
  const cust=users.find(u=>u.type==="customer")||{};
  const agents=users.filter(u=>u.type==="agent" && (u.id||"").includes("@"));
  const dt=pht(t.created_at);
  const gids=((t.access||{}).group_ids)||[], gid=gids.length?gids[gids.length-1]:null;
  let ratingLabel=null, hasComment=false, comment="", concern="";
  const custTexts=[], humanTexts=[], transcript=[], bots=[];
  let firstC=null, firstH=null;
  for(const ev of (t.events||[])){
    const et=ev.type;
    if(et==="filled_form"){
      for(const f of (ev.fields||[])){
        const lbl=(f.label||"").toLowerCase(); const ans=f.answer; const val=(ans&&typeof ans==="object")?ans.label:ans;
        if(lbl.includes("rate your experience")) ratingLabel=String(val);
        else if(lbl.includes("concern")) concern=String(val);
        else if(lbl.includes("comment")||lbl.includes("feedback")||lbl.includes("remarks")){ if(val){hasComment=true; comment=String(val);} }
      }
      continue;
    }
    const sm=ev.system_message_type;
    if(sm==="rating.chat_rated"){ const sc=(ev.text_vars||{}).score; ratingLabel=ratingLabel||(sc==="good"?"Good":"A lot to improve!"); }
    else if(sm==="rating.chat_commented"){ hasComment=true; comment=ev.text||comment; }
    if(et==="message"||et==="rich_message"){
      const a=ev.author_id; const tx=(ev.text||"").replace(/\n/g," ").trim();
      const e2=pht(ev.created_at); const ts=fmtT(e2);
      if(a===cust.id){ if(tx){ custTexts.push(tx); transcript.push({role:"customer",name:cust.name||"Customer",t:ts,text:tx.slice(0,500)}); } if(firstC===null) firstC=ev.created_at; }
      else{
        const au=users.find(u=>u.id===a)||{}; const nm=au.name||"";
        if((a||"").includes("@")){ if(tx){ humanTexts.push(tx); transcript.push({role:"agent",name:nm||"Agent",t:ts,text:tx.slice(0,500)}); } if(firstH===null) firstH=ev.created_at; }
        else if(tx){ transcript.push({role:"bot",name:nm||"Bot",t:ts,text:tx.slice(0,500)}); if(nm&&!bots.includes(nm)) bots.push(nm); }
      }
    }
  }
  const lab=(ratingLabel||"").toLowerCase();
  let rating=null;
  if(["excellent!","good","excellent"].includes(lab)) rating="good";
  else if(["could be better","could be better!","a lot to improve!","a lot to improve","bad"].includes(lab)) rating="bad";
  const labels=classify(custTexts, humanTexts, rating);
  const itype=issueType(concern, labels, custTexts);
  const [err,sol]=detectError(custTexts, humanTexts, labels);
  let problem=summarize(custTexts); if(comment) problem=(problem?problem+"  | comment: ":"comment: ")+comment.slice(0,160);
  const nc=custTexts.length, nh=humanTexts.length, nb=transcript.filter(m=>m.role==="bot").length;
  const ureason = rating?"":(nc===0&&nh===0&&nb===0)?"No messages at all":(nc===0&&nh===0&&nb>0)?"Bot only - customer never typed":(nc===0&&nh>0)?"Agent only - customer never typed":(nh===0&&nc>0)?"Customer wrote, no human agent replied":"Agent handled - customer just didn't rate";
  let fr=null; if(firstC&&firstH) fr=Math.round((Date.parse(firstH)-Date.parse(firstC))/1000);
  return { chat_id:c.id, time:fmtDT(dt), group_id:gid, group_name:groups[gid]||"", customer:cust.name||"(unknown)", customer_id:cust.id||"",
    rating:rating||"unrated", rating_label:ratingLabel||"", has_comment:hasComment, comment, concern,
    agents:agents.map(a=>({name:a.name,id:a.id})), n_agents:agents.length, bots, bot_only:agents.length===0,
    issue_type:itype, unrated_reason:ureason, problem, error:err, classification:labels, suggestion:sol, first_response:fr,
    link:`https://my.livechatinc.com/archives/${c.id}?query=${c.id}`, transcript };
}

async function fetchGroupDay(env, date, group, ratedOnly, groups){
  const {from,to}=dayRange(date);
  const rows=[]; let page=null, pages=0;
  while(true){
    const body = page ? {page_id:page} : {limit:100, sort_order:"asc", filters:{from,to,group_ids:[parseInt(group)]}};
    const r = await lcPost(env, LC_API+"list_archives", body);
    if(!r.ok) break;
    const d = await r.json(); const cs=d.chats||[];
    for(const c of cs) rows.push(buildRow(c, groups));
    pages++; page=d.next_page_id;
    if(!page||!cs.length||pages>=MAX_PAGES) break;
  }
  return ratedOnly ? rows.filter(r=>r.rating==="bad"||r.rating==="good") : rows;
}

async function handleReport(url, env){
  const date=url.searchParams.get("date"), group=url.searchParams.get("group");
  const ratedOnly = url.searchParams.get("rated")!=="0";
  if(!date||!group) return json({error:"date and group required"},400);
  const refresh = url.searchParams.get("refresh")==="1";
  const key = `r:${date}:${group}:${ratedOnly?1:0}`;
  if(!refresh && env.LC_KV){
    const cached = await env.LC_KV.get(key, "json");
    if(cached) return json({date, group, rows:cached, cached:true});
  }
  const groups = await getGroups(env);
  const rows = await fetchGroupDay(env, date, group, ratedOnly, groups);
  if(env.LC_KV) await env.LC_KV.put(key, JSON.stringify(rows), { expirationTtl: 259200 });
  return json({date, group, rows, cached:false});
}

async function handleLogin(request, env){
  let body={}; try{ body=await request.json(); }catch(e){}
  const ok = String(body.user||"") === String(env.ADMIN_USER||"\u0000") && String(body.pass||"") === String(env.ADMIN_PASSWORD||"\u0000");
  if(!ok) return json({error:"Invalid username or password."}, 401);
  const tok = await makeSession("Admin", env.SESSION_SECRET);
  return new Response(JSON.stringify({ok:true}), {status:200, headers:{
    "content-type":"application/json; charset=utf-8",
    "Set-Cookie":`lcmon=${tok}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${SESSION_HOURS*3600}`,
    "cache-control":"no-store"}});
}

export default {
  async fetch(request, env){
    const url = new URL(request.url);
    const p = url.pathname;
    if(p==="/favicon.svg") return new Response(b64toUtf8(FAVICON_B64), {headers:{"content-type":"image/svg+xml","cache-control":"public, max-age=86400"}});
    if(p==="/login"||p==="/login.html") return html(b64toUtf8(LOGIN_HTML_B64));
    if(p==="/api/login" && request.method==="POST") return handleLogin(request, env);
    if(p==="/api/logout") return new Response(JSON.stringify({ok:true}), {status:200, headers:{"content-type":"application/json","Set-Cookie":"lcmon=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0","cache-control":"no-store"}});
    const user = await getUser(request, env);
    if(p.startsWith("/api/")){
      if(!user) return json({error:"unauthorized"},401);
      if(p==="/api/groups") return json(await getGroups(env));
      if(p==="/api/report") return handleReport(url, env);
      return json({error:"not found"},404);
    }
    if(p==="/"||p==="/index.html"){
      if(!user) return html(b64toUtf8(LOGIN_HTML_B64));
      return html(b64toUtf8(DASH_HTML_B64));
    }
    return new Response("Not found", {status:404});
  }
};
